name: main

on: [push]

jobs:
  test-unit:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Unit tests (Node 14, Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules and dist
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            dist
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true

  test-release:
    if: github.ref != 'refs/heads/main'
    needs: test-unit
    name: Release (test run)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules and dist
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            dist
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Release package (test run)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --dry-run

  release:
    if: github.ref == 'refs/heads/main'

    needs: test-unit

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules and dist
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            dist
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Release package
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
