name: tests

on: [push]

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Unit tests (Node 14, Ubuntu)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true
