name: tests

on: [push]

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Unit tests (Node 14, Ubuntu)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules directory
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            dist
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true

  release-dry-run:
    needs: tests

    name: Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release (dry-run)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --dry-run
